/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mengnonton;

import com.jtattoo.plaf.aluminium.AluminiumLookAndFeel;
import java.awt.Color;
import java.awt.Component;
import java.awt.EventQueue;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.AbstractCellEditor;
import javax.swing.ButtonModel;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author dblenk
 */
public class VBayarTiket extends javax.swing.JFrame {

    /**
     * Creates new form VMakanan
     */
     Color SoftBlue = new Color(17,142,234,255);
     Color HardBlue = new Color(26,44,80);
        
    public VBayarTiket() {
        initComponents();
      
        
        this.setExtendedState(VBayarTiket.MAXIMIZED_BOTH);
        tabelTiket.getTableHeader().setFont(new Font("Lato", Font.BOLD, 17));

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tabelTiket.setDefaultRenderer(String.class, centerRenderer);

        DefaultTableCellRenderer centerInt = new DefaultTableCellRenderer();
        centerInt.setHorizontalAlignment(JLabel.CENTER);
        tabelTiket.setDefaultRenderer(Integer.class, centerInt);
        tabelTiket.setRowHeight(30);

        tabelTiket.getColumn("Aksi").setCellRenderer(new ButtonRenderer());
        tabelTiket.getColumn("Aksi").setCellEditor(
                new ButtonEditor(new JCheckBox()));

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        sidepanel = new javax.swing.JPanel();
        MJudul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MPembayaran = new javax.swing.JButton();
        MLogout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LMakanan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTiket = new javax.swing.JTable();
        FormIDTiket = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        BSimpan = new javax.swing.JButton();
        back = new javax.swing.JButton();
        ToggleA1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        ToggleA2 = new javax.swing.JToggleButton();
        ToggleA3 = new javax.swing.JToggleButton();
        ToggleA4 = new javax.swing.JToggleButton();
        ToggleB1 = new javax.swing.JToggleButton();
        ToggleB2 = new javax.swing.JToggleButton();
        ToggleB3 = new javax.swing.JToggleButton();
        ToggleB4 = new javax.swing.JToggleButton();
        ToggleC1 = new javax.swing.JToggleButton();
        ToggleC2 = new javax.swing.JToggleButton();
        ToggleC3 = new javax.swing.JToggleButton();
        ToggleC4 = new javax.swing.JToggleButton();
        ToggleA5 = new javax.swing.JToggleButton();
        ToggleA6 = new javax.swing.JToggleButton();
        ToggleA7 = new javax.swing.JToggleButton();
        ToggleA8 = new javax.swing.JToggleButton();
        ToggleB8 = new javax.swing.JToggleButton();
        ToggleB7 = new javax.swing.JToggleButton();
        ToggleB6 = new javax.swing.JToggleButton();
        ToggleB5 = new javax.swing.JToggleButton();
        ToggleC5 = new javax.swing.JToggleButton();
        ToggleC6 = new javax.swing.JToggleButton();
        ToggleB15 = new javax.swing.JToggleButton();
        ToggleB16 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(1000, 700));

        sidepanel.setBackground(new java.awt.Color(0, 8, 66));
        sidepanel.setForeground(new java.awt.Color(255, 255, 255));
        sidepanel.setFont(new java.awt.Font("Lato", 0, 11)); // NOI18N
        sidepanel.setPreferredSize(new java.awt.Dimension(325, 700));

        MJudul.setBackground(new java.awt.Color(255, 255, 255));
        MJudul.setFont(new java.awt.Font("Lato", 1, 30)); // NOI18N
        MJudul.setForeground(new java.awt.Color(255, 255, 255));
        MJudul.setText("MengNonton");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("______________________________");

        MPembayaran.setBackground(new java.awt.Color(0, 8, 66));
        MPembayaran.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        MPembayaran.setForeground(new java.awt.Color(255, 255, 255));
        MPembayaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bayar.png"))); // NOI18N
        MPembayaran.setText("Pembayaran");
        MPembayaran.setBorder(null);
        MPembayaran.setBorderPainted(false);
        MPembayaran.setContentAreaFilled(false);
        MPembayaran.setHideActionText(true);
        MPembayaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MPembayaran.setIconTextGap(10);
        MPembayaran.setPreferredSize(new java.awt.Dimension(97, 32));
        MPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPembayaranActionPerformed(evt);
            }
        });

        MLogout.setBackground(new java.awt.Color(0, 8, 66));
        MLogout.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        MLogout.setForeground(new java.awt.Color(255, 255, 255));
        MLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/logout.png"))); // NOI18N
        MLogout.setText("Logout");
        MLogout.setBorder(null);
        MLogout.setBorderPainted(false);
        MLogout.setContentAreaFilled(false);
        MLogout.setHideActionText(true);
        MLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        MLogout.setIconTextGap(10);
        MLogout.setPreferredSize(new java.awt.Dimension(97, 32));
        MLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MJudul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MPembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(MJudul)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(MPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(MLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(12, 33, 193));
        jPanel2.setPreferredSize(new java.awt.Dimension(675, 102));

        LMakanan.setBackground(new java.awt.Color(255, 255, 255));
        LMakanan.setFont(new java.awt.Font("Lato", 0, 24)); // NOI18N
        LMakanan.setForeground(new java.awt.Color(255, 255, 255));
        LMakanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/bayar.png"))); // NOI18N
        LMakanan.setText("Pembayaran");

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Menu Pembayaran Tiket");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(LMakanan))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LMakanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tabelTiket.setFont(new java.awt.Font("Lato", 0, 17)); // NOI18N
        tabelTiket.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(1), null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Studio", "Film", "", "Aksi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelTiket.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(tabelTiket);
        if (tabelTiket.getColumnModel().getColumnCount() > 0) {
            tabelTiket.getColumnModel().getColumn(0).setMinWidth(25);
            tabelTiket.getColumnModel().getColumn(0).setPreferredWidth(25);
            tabelTiket.getColumnModel().getColumn(0).setMaxWidth(25);
            tabelTiket.getColumnModel().getColumn(4).setMinWidth(120);
            tabelTiket.getColumnModel().getColumn(4).setPreferredWidth(120);
            tabelTiket.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        FormIDTiket.setFont(new java.awt.Font("Lato", 0, 17)); // NOI18N
        FormIDTiket.setForeground(new java.awt.Color(0, 6, 66));
        FormIDTiket.setMaximumRowCount(5);
        FormIDTiket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Studio 1 | Doraemon 12.00 - 14.00", "Studio 2 | Doraemon Movie 18.00 - 19.00" }));

        jLabel7.setFont(new java.awt.Font("Lato", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Jadwal Tiket");

        BSimpan.setBackground(new java.awt.Color(12, 33, 193));
        BSimpan.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        BSimpan.setForeground(new java.awt.Color(255, 255, 255));
        BSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/simpan.png"))); // NOI18N
        BSimpan.setText("SIMPAN");
        BSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSimpanActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(238, 210, 2));
        back.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/back.png"))); // NOI18N
        back.setText("Kembali");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        ToggleA1.setBackground(new java.awt.Color(26, 44, 80));
        ToggleA1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleA1.setForeground(new java.awt.Color(255, 255, 255));
        ToggleA1.setText("A1");
        ToggleA1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleA1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(26, 44, 80));
        jButton1.setBorder(null);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Tersedia");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Tidak Tersedia");

        jButton2.setBackground(new java.awt.Color(153, 153, 153));
        jButton2.setBorder(null);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Pilihanmu");

        jButton3.setBackground(new java.awt.Color(17, 142, 234));
        jButton3.setBorder(null);

        ToggleA2.setBackground(new java.awt.Color(26, 44, 80));
        ToggleA2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleA2.setForeground(new java.awt.Color(255, 255, 255));
        ToggleA2.setText("A2");
        ToggleA2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleA2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleA2ActionPerformed(evt);
            }
        });

        ToggleA3.setBackground(new java.awt.Color(235, 236, 238));
        ToggleA3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleA3.setForeground(new java.awt.Color(255, 255, 255));
        ToggleA3.setText("A3");
        ToggleA3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleA3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleA3ActionPerformed(evt);
            }
        });

        ToggleA4.setBackground(new java.awt.Color(235, 236, 238));
        ToggleA4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleA4.setForeground(new java.awt.Color(255, 255, 255));
        ToggleA4.setText("A4");
        ToggleA4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleA4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleA4ActionPerformed(evt);
            }
        });

        ToggleB1.setBackground(new java.awt.Color(26, 44, 80));
        ToggleB1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB1.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB1.setText("B1");
        ToggleB1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB1ActionPerformed(evt);
            }
        });

        ToggleB2.setBackground(new java.awt.Color(26, 44, 80));
        ToggleB2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB2.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB2.setText("B2");
        ToggleB2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB2ActionPerformed(evt);
            }
        });

        ToggleB3.setBackground(new java.awt.Color(235, 236, 238));
        ToggleB3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB3.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB3.setText("B3");
        ToggleB3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB3ActionPerformed(evt);
            }
        });

        ToggleB4.setBackground(new java.awt.Color(235, 236, 238));
        ToggleB4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB4.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB4.setText("B4");
        ToggleB4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB4ActionPerformed(evt);
            }
        });

        ToggleC1.setBackground(new java.awt.Color(26, 44, 80));
        ToggleC1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleC1.setForeground(new java.awt.Color(255, 255, 255));
        ToggleC1.setText("C1");
        ToggleC1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleC1ActionPerformed(evt);
            }
        });

        ToggleC2.setBackground(new java.awt.Color(26, 44, 80));
        ToggleC2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleC2.setForeground(new java.awt.Color(255, 255, 255));
        ToggleC2.setText("C2");
        ToggleC2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleC2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleC2ActionPerformed(evt);
            }
        });

        ToggleC3.setBackground(new java.awt.Color(235, 236, 238));
        ToggleC3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleC3.setForeground(new java.awt.Color(255, 255, 255));
        ToggleC3.setText("C3");
        ToggleC3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleC3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleC3ActionPerformed(evt);
            }
        });

        ToggleC4.setBackground(new java.awt.Color(235, 236, 238));
        ToggleC4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleC4.setForeground(new java.awt.Color(255, 255, 255));
        ToggleC4.setText("C4");
        ToggleC4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleC4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleC4ActionPerformed(evt);
            }
        });

        ToggleA5.setBackground(new java.awt.Color(26, 44, 80));
        ToggleA5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleA5.setForeground(new java.awt.Color(255, 255, 255));
        ToggleA5.setText("A5");
        ToggleA5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleA5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleA5ActionPerformed(evt);
            }
        });

        ToggleA6.setBackground(new java.awt.Color(26, 44, 80));
        ToggleA6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleA6.setForeground(new java.awt.Color(255, 255, 255));
        ToggleA6.setText("A6");
        ToggleA6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleA6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleA6ActionPerformed(evt);
            }
        });

        ToggleA7.setBackground(new java.awt.Color(235, 236, 238));
        ToggleA7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleA7.setForeground(new java.awt.Color(255, 255, 255));
        ToggleA7.setText("A7");
        ToggleA7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleA7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleA7ActionPerformed(evt);
            }
        });

        ToggleA8.setBackground(new java.awt.Color(235, 236, 238));
        ToggleA8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleA8.setForeground(new java.awt.Color(255, 255, 255));
        ToggleA8.setText("A8");
        ToggleA8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleA8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleA8ActionPerformed(evt);
            }
        });

        ToggleB8.setBackground(new java.awt.Color(235, 236, 238));
        ToggleB8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB8.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB8.setText("B8");
        ToggleB8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB8ActionPerformed(evt);
            }
        });

        ToggleB7.setBackground(new java.awt.Color(235, 236, 238));
        ToggleB7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB7.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB7.setText("B7");
        ToggleB7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB7ActionPerformed(evt);
            }
        });

        ToggleB6.setBackground(new java.awt.Color(26, 44, 80));
        ToggleB6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB6.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB6.setText("B6");
        ToggleB6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB6ActionPerformed(evt);
            }
        });

        ToggleB5.setBackground(new java.awt.Color(26, 44, 80));
        ToggleB5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB5.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB5.setText("B5");
        ToggleB5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB5ActionPerformed(evt);
            }
        });

        ToggleC5.setBackground(new java.awt.Color(26, 44, 80));
        ToggleC5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleC5.setForeground(new java.awt.Color(255, 255, 255));
        ToggleC5.setText("C5");
        ToggleC5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleC5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleC5ActionPerformed(evt);
            }
        });

        ToggleC6.setBackground(new java.awt.Color(26, 44, 80));
        ToggleC6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleC6.setForeground(new java.awt.Color(255, 255, 255));
        ToggleC6.setText("C2");
        ToggleC6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleC6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleC6ActionPerformed(evt);
            }
        });

        ToggleB15.setBackground(new java.awt.Color(235, 236, 238));
        ToggleB15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB15.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB15.setText("C3");
        ToggleB15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB15ActionPerformed(evt);
            }
        });

        ToggleB16.setBackground(new java.awt.Color(235, 236, 238));
        ToggleB16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        ToggleB16.setForeground(new java.awt.Color(255, 255, 255));
        ToggleB16.setText("C4");
        ToggleB16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ToggleB16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleB16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bgLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addContainerGap(538, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FormIDTiket, javax.swing.GroupLayout.Alignment.LEADING, 0, 507, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(ToggleB1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ToggleB2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(ToggleA1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ToggleA2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(ToggleC1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ToggleC2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 80, 80)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addComponent(ToggleB3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ToggleB4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addComponent(ToggleA3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ToggleA4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bgLayout.createSequentialGroup()
                                        .addComponent(ToggleC3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ToggleC4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addComponent(ToggleB5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ToggleB6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(bgLayout.createSequentialGroup()
                                            .addComponent(ToggleA5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(ToggleA6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(bgLayout.createSequentialGroup()
                                        .addComponent(ToggleC5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ToggleC6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(80, 80, 80)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addComponent(ToggleB7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ToggleB8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addComponent(ToggleA7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ToggleA8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                                        .addComponent(ToggleB15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ToggleB16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(102, 102, 102))))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addComponent(sidepanel, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FormIDTiket, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ToggleA1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleA2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleA3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleA4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ToggleB1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleB2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleB3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleB4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ToggleC1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleC2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleC3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleC4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ToggleA5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleA6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ToggleB5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleB6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ToggleC5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ToggleC6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToggleA7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToggleA8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToggleB7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToggleB8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ToggleB15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToggleB16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        getContentPane().add(bg);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        new VBayar().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void BSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSimpanActionPerformed
        // TODO add your handling code here:
        new VBayar().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BSimpanActionPerformed

    private void MLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MLogoutActionPerformed
        // TODO add your handling code here:
        new VLogin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MLogoutActionPerformed

    private void MPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPembayaranActionPerformed
        // TODO add your handling code here:
        new VBayar().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_MPembayaranActionPerformed

    private void ToggleA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleA1ActionPerformed
        // TODO add your handling code here:
        
        if (ToggleA1.isSelected()) {
            ToggleA1.setBackground(SoftBlue);
        }else {
            ToggleA1.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleA1ActionPerformed

    private void ToggleA2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleA2ActionPerformed
        // TODO add your handling code here:
        if (ToggleA2.isSelected()) {
            ToggleA2.setBackground(SoftBlue);
        }else {
            ToggleA2.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleA2ActionPerformed

    private void ToggleA3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleA3ActionPerformed
        // TODO add your handling code here:
         ToggleA3.setEnabled(false);
    }//GEN-LAST:event_ToggleA3ActionPerformed

    private void ToggleA4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleA4ActionPerformed
        // TODO add your handling code here:
         ToggleA3.setEnabled(false);
    }//GEN-LAST:event_ToggleA4ActionPerformed

    private void ToggleB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB1ActionPerformed
        // TODO add your handling code here:
         
        if (ToggleB1.isSelected()) {
            ToggleB1.setBackground(SoftBlue);
        }else {
            ToggleB1.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleB1ActionPerformed

    private void ToggleB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB2ActionPerformed
        // TODO add your handling code here:

        if (ToggleB2.isSelected()) {
            ToggleB2.setBackground(SoftBlue);
        }else {
            ToggleB2.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleB2ActionPerformed

    private void ToggleB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleB3ActionPerformed

    private void ToggleB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleB4ActionPerformed

    private void ToggleC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleC1ActionPerformed
        // TODO add your handling code here:
        if (ToggleC1.isSelected()) {
            ToggleC1.setBackground(SoftBlue);
        }else {
            ToggleC1.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleC1ActionPerformed

    private void ToggleC2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleC2ActionPerformed
        // TODO add your handling code here:
        if (ToggleC2.isSelected()) {
            ToggleC2.setBackground(SoftBlue);
        }else {
            ToggleC2.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleC2ActionPerformed

    private void ToggleC3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleC3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleC3ActionPerformed

    private void ToggleC4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleC4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleC4ActionPerformed

    private void ToggleA5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleA5ActionPerformed
        // TODO add your handling code here:
        if (ToggleA5.isSelected()) {
            ToggleA5.setBackground(SoftBlue);
        }else {
            ToggleA5.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleA5ActionPerformed

    private void ToggleA6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleA6ActionPerformed
        // TODO add your handling code here:
        if (ToggleA6.isSelected()) {
            ToggleA6.setBackground(SoftBlue);
        }else {
            ToggleA6.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleA6ActionPerformed

    private void ToggleA7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleA7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleA7ActionPerformed

    private void ToggleA8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleA8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleA8ActionPerformed

    private void ToggleB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleB8ActionPerformed

    private void ToggleB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleB7ActionPerformed

    private void ToggleB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB6ActionPerformed
        // TODO add your handling code here:
        if (ToggleB6.isSelected()) {
            ToggleB6.setBackground(SoftBlue);
        }else {
            ToggleB6.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleB6ActionPerformed

    private void ToggleB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB5ActionPerformed
        // TODO add your handling code here:
        if (ToggleB5.isSelected()) {
            ToggleB5.setBackground(SoftBlue);
        }else {
            ToggleB5.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleB5ActionPerformed

    private void ToggleC5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleC5ActionPerformed
        // TODO add your handling code here:
        if (ToggleC5.isSelected()) {
            ToggleC5.setBackground(SoftBlue);
        }else {
            ToggleC5.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleC5ActionPerformed

    private void ToggleC6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleC6ActionPerformed
        // TODO add your handling code here:
        if (ToggleC6.isSelected()) {
            ToggleC6.setBackground(SoftBlue);
        }else {
            ToggleC6.setBackground(HardBlue);
        }
    }//GEN-LAST:event_ToggleC6ActionPerformed

    private void ToggleB15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleB15ActionPerformed

    private void ToggleB16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleB16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ToggleB16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VBayarTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VBayarTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VBayarTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VBayarTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(new AluminiumLookAndFeel());

                } catch (Exception e) {
                }
                new VBayarTiket().setVisible(true);
            }
        });
    }

    class ButtonRenderer extends JButton implements TableCellRenderer {

        public ButtonRenderer() {
            setOpaque(true);
            setFont(new Font("Lato", 0, 17)); // NOI18N

        }

        public Component getTableCellRendererComponent(JTable table, Object value,
                boolean isSelected, boolean hasFocus, int row, int column) {
            if (isSelected) {
                setForeground(table.getForeground());
                setBackground(UIManager.getColor("Button.background"));
            } else {
                setForeground(table.getForeground());
                setBackground(UIManager.getColor("Button.background"));
            }
            setText((value == null) ? "Hapus" : value.toString());
            return this;
        }
    }

    /**
     * @version 1.0 11/09/98
     */
    class ButtonEditor extends DefaultCellEditor {

        protected JButton button;
        protected JButton btnDel;

        private String label;

        private boolean isPushed;
//    ButtonTambah.setBackground(new java.awt.Color(12, 33, 193));
//        ButtonTambah.setFont(new java.awt.Font("Lato", 0, 17)); // NOI18N
//        ButtonTambah.setForeground(new java.awt.Color(255, 255, 255));
//        ButtonTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tambah.png"))); // NOI18N
//        ButtonTambah.setText("Tambah");
//        ButtonTambah.setPreferredSize(new java.awt.Dimension(141, 43));
//        ButtonTambah.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                ButtonTambahActionPerformed(evt);
//            }
//        });

        public ButtonEditor(JCheckBox checkBox) {
            super(checkBox);
            button = new JButton();
            button.setBackground(new Color(12, 33, 193));
            button.setFont(new java.awt.Font("Lato", 0, 17)); // NOI18N
            button.setForeground(new Color(255, 255, 255));
            button.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    fireEditingStopped();
                }
            });

        }

        public Component getTableCellEditorComponent(JTable table, Object value,
                boolean isSelected, int row, int column) {
            if (isSelected) {
                button.setBackground(new Color(12, 33, 193));
                button.setFont(new Font("Lato", 0, 17)); // NOI18N
                button.setBorder(null);
                button.setBorderPainted(false);
                button.setContentAreaFilled(false);
                button.setForeground(new Color(255, 255, 255));
            } else {
                button.setBackground(new Color(12, 33, 193));
                button.setFont(new Font("Lato", 0, 17)); // NOI18N
                button.setBorder(null);
                button.setBorderPainted(false);
                button.setContentAreaFilled(false);
                button.setForeground(new Color(255, 255, 255));
            }
            label = (value == null) ? "Hapus" : value.toString();
            button.setText(label);
            isPushed = true;
            return button;
        }

        public Object getCellEditorValue() {
            if (isPushed) {
//            new VEditFilm().setVisible(true);
                JOptionPane.showMessageDialog(rootPane, ": Apakah anda ingin menghapus data tersebut ?");
                // System.out.println(label + ": Ouch!");
            }
            isPushed = false;
            return new String(label);
        }

        public boolean stopCellEditing() {
            isPushed = false;
            return super.stopCellEditing();
        }

        protected void fireEditingStopped() {
            super.fireEditingStopped();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSimpan;
    private javax.swing.JComboBox<String> FormIDTiket;
    private javax.swing.JLabel LMakanan;
    private javax.swing.JLabel MJudul;
    private javax.swing.JButton MLogout;
    private javax.swing.JButton MPembayaran;
    private javax.swing.JToggleButton ToggleA1;
    private javax.swing.JToggleButton ToggleA2;
    private javax.swing.JToggleButton ToggleA3;
    private javax.swing.JToggleButton ToggleA4;
    private javax.swing.JToggleButton ToggleA5;
    private javax.swing.JToggleButton ToggleA6;
    private javax.swing.JToggleButton ToggleA7;
    private javax.swing.JToggleButton ToggleA8;
    private javax.swing.JToggleButton ToggleB1;
    private javax.swing.JToggleButton ToggleB15;
    private javax.swing.JToggleButton ToggleB16;
    private javax.swing.JToggleButton ToggleB2;
    private javax.swing.JToggleButton ToggleB3;
    private javax.swing.JToggleButton ToggleB4;
    private javax.swing.JToggleButton ToggleB5;
    private javax.swing.JToggleButton ToggleB6;
    private javax.swing.JToggleButton ToggleB7;
    private javax.swing.JToggleButton ToggleB8;
    private javax.swing.JToggleButton ToggleC1;
    private javax.swing.JToggleButton ToggleC2;
    private javax.swing.JToggleButton ToggleC3;
    private javax.swing.JToggleButton ToggleC4;
    private javax.swing.JToggleButton ToggleC5;
    private javax.swing.JToggleButton ToggleC6;
    private javax.swing.JButton back;
    private javax.swing.JPanel bg;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTable tabelTiket;
    // End of variables declaration//GEN-END:variables
}
